[package]
name = "st3215"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-io-async = "0.6.1"
tinyvec = "1.8.1"

[dev-dependencies]
futures-test = "0.3.31"
embedded-io-async = {features = ["std"], version = "0.6.1"}
