[package]
name = "st3215"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-io-async = "0.6.1"
embedded-io = "0.6.1"
tinyvec = "1.8.1"
bitflags = "1.3.2"

[dev-dependencies]
futures-test = "0.3.31"
embedded-io-async = {features = ["std"], version = "0.6.1"}
embedded-io = {features = ["std"], version = "0.6.1"}
embedded-io-adapters = {features = ["std"], version = "0.6.1"}
serialport = "3.1.1"
