[package]
name = "hovercontrol"
authors = ["Andrew Walbran <qwandor@gmail.com>"]
edition = "2018"
version = "0.1.0"

[dependencies]
color-backtrace = "0.5.1"
eyre = "0.6.5"
gilrs = "0.8.1"
homie-device = "0.6.0"
log = "0.4.14"
messages = { path = "../messages" }
nb = "1.1.0"
pretty_env_logger = "0.4.0"
rumqttc = "0.8.0"
rustls = "0.21.2"
rustls-native-certs = "0.5.0"
serde_derive = "1.0.130"
serde = "1.0.130"
serialport = "4.2.1"
stable-eyre = "0.2.2"
# TODO: Remove "io-util" and "macros" once a new version of rumqttc is released which fixes
# https://github.com/bytebeamio/rumqtt/issues/294.
tokio = { version = "1.19.2", features = ["io-util", "macros", "rt", "rt-multi-thread"] }
toml = "0.5.8"
