[package]
name = "hovercontrol"
authors = ["Andrew Walbran <qwandor@gmail.com>"]
edition = "2018"
version = "0.1.0"

[dependencies]
color-backtrace = "0.5.0"
eyre = "0.6.5"
gilrs = "0.8.1"
homie-device = "0.5.0"
log = "0.4.14"
messages = { path = "../messages" }
nb = "1.0.0"
pretty_env_logger = "0.4.0"
rumqttc = "0.4.0"
rustls = "0.19.0"
rustls-native-certs = "0.5.0"
serde_derive = "1.0.126"
serde = "1.0.126"
serialport = "4.0.0"
stable-eyre = "0.2.2"
tokio = { version = "1.8.1", features = ["rt"] }
toml = "0.5.8"
