[package]
name = "hovercontrol"
authors = ["Andrew Walbran <qwandor@gmail.com>"]
edition = "2018"
version = "0.1.0"

[dependencies]
color-backtrace = "0.5.0"
eyre = "0.6.5"
gilrs = "0.8.1"
pretty_env_logger = "0.4.0"
serialport = "4.0.0"
stable-eyre = "0.2.2"
