[package]
name = "hoverkite-protocol"
version = "0.1.0"
authors = ["David Laban <alsuren@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.4"
nb = "1.0.0"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"

[features]
default = ["std"]
std = []
