[package]
name = "kitebox-messages"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies.capnp]
version = "*"
default-features = false
features = ["unaligned"]

[build-dependencies.capnpc]
version = "*"
