[target.xtensa-esp32-none-elf]
# `in` is https://crates.io/crates/in-directory
runner = "in ../../kiteboxcontrol cargo +stable run -- flash"

[env]
ESP_LOG="INFO"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
